name: AvoRed Deployment via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
          script: |
            whoami
            ls -al
        env:
          CI: true
